# Generated by Django 2.1.5 on 2022-09-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itp', '0002_auto_20220908_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, unique=True)),
                ('time', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, unique=True)),
                ('time', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(blank=True, max_length=300)),
                ('paticipant', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, unique=True)),
                ('type', models.CharField(blank=True, choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Technical Reports', 'Technical Reports')], max_length=300)),
                ('year', models.IntegerField()),
                ('magazine', models.CharField(blank=True, max_length=300)),
                ('page', models.CharField(blank=True, max_length=300)),
                ('doi', models.CharField(blank=True, max_length=300)),
                ('conferenceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itp.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itp.Publication')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='publication_author',
            unique_together={('publication', 'author')},
        ),
    ]
