# Generated by Django 2.1.5 on 2022-09-08 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itp', '0005_remove_publication_conferenceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='paticipant',
            new_name='participant',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
