# Generated by Django 2.1.5 on 2022-09-09 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itp', '0006_auto_20220908_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='conferenceid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itp.Conference'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(help_text='Use cmd to select multiple authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
