# Generated by Django 2.1.5 on 2022-09-09 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itp', '0008_auto_20220909_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(help_text="<button><a href='add_author/'>Add An Author</a></button>Use cmd to select multiple authors", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conferenceid',
            field=models.ForeignKey(blank=True, help_text="<button><a href='add_conference/'>Add A Conference</a></button>", null=True, on_delete=django.db.models.deletion.CASCADE, to='itp.Conference'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text="<button><a href='add_tag/'>Add A Tag</a></button>", to='itp.Tag'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
